### ISSUE TITLE
Kickoff

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/dem2vectorterrain#1]
Discuss available data sources, flow and plan for the project.

Result should be visible in the README.md on this project.

**Comment by klokan** [comment]
@stirringhalo - available for Skype / Hangout? Check your email please...

**Comment by klokan** [comment]
Done. Thanks for the call @stirringhalo

**Comment by klokan** [comment]
@stirringhalo is interested esp. in hillshade vector tiles. We are going to use RAW DEM data from OpenSnowMap project - http://blog.opensnowmap.org/post/2015/10/25/Relief-layer-updated

**Comment by lukasmartinelli** [comment]
> @stirringhalo is interested esp. in hillshade vector tiles. We are going to use RAW DEM data from OpenSnowMap project - http://blog.opensnowmap.org/post/2015/10/25/Relief-layer-updated
>  👍 1

So it is really possible to create vector hill shade polygons as Mapbox does it with this data source?

**Comment by klokan** [comment]
Yes, it is possible - but it means rendering the raster hillshading with correct paramters (combined with slopeshading probably, etc), then vectorisation (either on range of colors or on a posterised image with limited number of colors) - all of this on 285 GB of raster data.
After we have vectors do import into PostGIS, generalization for upper zoom levels, finetuning of .tm2 and use of workers in docker on a cluster to get the tiles.

**Comment by klokan** [comment]
The contour lines are low-hanging fruit, as we have shapefiles ready to be used. Only import into PostGIS, assigning of extra attributes, making .tm2 and rendering. It has a lower priority for @stirringhalo - he is keen on vector hillshading.
If anybody is interested (@lukasmartinelli?) I can advise, it is probably a work for one weekend with the knowledge of the OSM2VectorTiles project.

**Comment by ghost** [comment]
I have the OpenSnowMap DEM fully downloaded, and I'll do some experimentation in my free time to get posterize and dumping to vectors working (probably using polygonize). I think it's doable, but it's lots of reverse engineering to get something looking similar while still being style compatible

**Comment by ghost** [comment]
In light of #3, this is on hold until we can come up with a different schema and style that respects Mapbox licensing. I had not seen the issue (https://github.com/osm2vectortiles/mapbox-gl-styles/issues/3) until after the previous comment was made.

**Comment by alexandervlpl** [comment]
@stirringhalo : Are the OpenSnowMap DEMs freely available somewhere? Is it possible to use this data?
