### ISSUE TITLE
Any progress on polygons from hillshades?

### ISSUE THREAD

**Issue by kingcu** [osm2vectortiles/dem2vectorterrain#2]
I ran across this repo while looking for existing tools to create vector hillshades. I have experimented with a handful of methods (gdal_polygonize on hillshade TIFFs, gdal_contour on same TIFFs, black/white representations of hillshades with both tools, and more) and have failed to get satisfactory results. Did you produce decent results using your method outlined? If so, do you have any tips or information to share before I head down the same path?

Any input is appreciated, cheers!

**Comment by ghost** [comment]
Sorry, not yet. Been busy with a couple upcoming due dates. Hopefully beginning of August I will start tackling this again.

**Comment by kingcu** [comment]
Awesome, i'll check back, thanks.

**Comment by ghost** [comment]
See #3
